# Generated by Django 4.2.3 on 2023-07-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
