# Generated by Django 4.2.3 on 2023-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='nation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
