# Generated by Django 4.2.3 on 2023-07-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('all', '전체관람가'), ('12', '12세 이상 관람가'), ('15', '15세 이상 관람가'), ('restricted', '청소년 관람불가'), ('limited', '제한상영가')], max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('director', '감독'), ('leading', '주연'), ('supporting', '조연')], max_length=20),
        ),
    ]
