# Generated by Django 4.2.3 on 2023-07-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_age_limit_alter_role_role_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='nation',
            new_name='country',
        ),
    ]
