# Generated by Django 4.2.3 on 2023-07-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('all', '전체관람가'), ('12', '12세 이상 관람가'), ('15', '15세 이상 관람가'), ('rated-R', '청소년 관람불가'), ('restricted', '제한상영가')], max_length=10),
        ),
    ]
