# Generated by Django 4.2.3 on 2023-07-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_comment_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'rating'), name='one_by_one'),
        ),
    ]
